cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    
    path('', views.product_list, name='product_list'),
    path('loginuser/',views.loginuser,name='loginuser'),
    # path('rate/<int:product_id>/<slug:slug>/', views.rate_product, name='rate_product'),
     

#     path('signupuser/',views.signupuser,name='signupuser'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'
         ),
    path('rate/<int:id>/<slug:slug>/', views.rate_product, name='rate_product'),
    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail'),

     
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class CustomUser(models.Model):
    username = models.OneToOneField(User, on_delete=models.PROTECT)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    password1 = models.CharField(max_length=50)
    password2 = models.CharField(max_length=50)
    class Meta:
        ordering = ('username',)
        verbose_name = 'User'
        verbose_name_plural = 'Userler'

    def __str__(self) -> str:
        return f'{self.username} {self.first_name} {self.last_name}'
    
    


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True)
    slug = models.CharField(max_length=150, db_index=True, unique=True)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(max_length=1000, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)

    ratings = models.ManyToManyField(CustomUser, through='Rating', related_name='rated_products')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class Rating(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    rated_product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        blank=True,default=3,
        )
    created_at = models.DateTimeField(auto_now_add=True)

shop/forms.py
from django import forms

class RatingForm(forms.Form):
    rating = forms.IntegerField(
        label='Рейтинг',
        min_value=1,
        max_value=5,
        widget=forms.NumberInput(attrs={'class': 'rating-input'})
    )

shop/views.py
from django.shortcuts import render, get_object_or_404,redirect
from cart.forms import CartAddProductForm
from .models import Category, Product,CustomUser,Rating
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import authenticate,login,logout
from .forms import RatingForm

from django.http import JsonResponse


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  })

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.cleaned_data['rating']
            user = request.user

            # Создаем объект оценки
            Rating.objects.create(user=user, product=product, rating=rating)

            # Можно добавить дополнительные действия после создания оценки, например, перенаправление на страницу товара
            return redirect('shop:product_detail', id=product.id, slug=product.slug)
    else:
        form = RatingForm()
    context =  {
        'product': product,
        'cart_product_form': cart_product_form,
        'form': form}

    return render(request, 'shop/product/detail.html',context)
# def product_detail(request, id, slug):
#     product = get_object_or_404(Product, id=id, slug=slug, available=True)
#     cart_product_form = CartAddProductForm()
#     return render(request, 'shop/product/detail.html', {'product': product,'cart_product_form':cart_product_form })

def loginuser(request,category_slug=None):
    if request.method == 'GET':
        return render(request,'loginuser.html',{'form':AuthenticationForm()})
    else:
        user = authenticate(request,username=request.POST['username'],password=request.POST['password'])
        if user is None:
            return render(request,'shop/loginuser.html',{'form':AuthenticationForm(),'error':'Qollaniwshi ati ya parol qate'})
        else:
            category = None
            categories = Category.objects.all()
            products = Product.objects.filter(available=True)
            if category_slug:
                category = get_object_or_404(Category, slug=category_slug)
                products = products.filter(category=category)
            return render(request, 'shop/product/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products,
                      'username':request.POST['username']

                  })



def rate_product(request, id,slug):
    product = get_object_or_404(Product, id=id,slug=slug)

    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.cleaned_data['rating']
            user = request.user

            # Создаем объект оценки
            Rating.objects.create(user=user, product=product, rating=rating)
            
            # Можно добавить дополнительные действия после создания оценки, например, перенаправление на страницу товара
            return redirect('shop:product_detail', id=product.id, slug=product.slug)
    else:
        form = RatingForm()

    return render(request, 'rate_product.html', {'form': form, 'product': product})
# def signupuser(request):
#     if request.method == 'GET':
#         return render(request,'shop/signupuser.html',{'form':UserCreationForm(),})
#     else:
#         if request.POST['password1'] == request.POST['password2']:
#             user=User.objects.create_user(request.POST['username'],password = request.POST['password1'])
#             user.save()
#             return redirect(request,'shop/loginuser.html')
#         else:
#             return render(request,'shop/signupuser.html',{'form':UserCreationForm(),'error':'Parol ya username qate'})




# def signupuser(request):
#     if request.method == 'POST':
#         form = SignupForm(request.POST)
#         if form.is_valid():
#             # Создание и сохранение нового пользователя
#             form.save()
#             return redirect('login')  # Перенаправление на страницу входа после успешной регистрации
#     else:
#         form = SignupForm()
#     return render(request, 'signup.html', {'form': form})

templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}>
<h1>{{ product.name }}</h1>
<h2>
<a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
</h2>
<p class="price">${{ product.price }}</p>
<form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Korzinkaga qosiw">
    

</form>
{{ product.description|linebreaks }}
</div>

{% if product.ratings.all %}
    <h3>Оценки товара</h3>
    <ul>
      {% for rating in product.ratings.all %}
        <li>{{ rating.rating }} (от {{ rating.user.username }})</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Пока нет оценок для этого товара.</p>
  {% endif %}

  <!-- Форма для оценки товара -->
  <h3>Оценить товар</h3>
<form method="post" action="{% url 'shop:rate_product' product.id product.slug %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Оценить</button>
</form>
{% endblock %}

templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
<h3>Category</h3>
<ul>
<li {% if not category %}class="selected"{% endif %}>
<a href="{% url 'shop:product_list' %}">Barligi</a>
</li>
{% for c in categories %}
<li {% if category.slug == c.slug %}class="selected" {% endif %}>
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
{% endfor %}
</ul>
</div>
<div id="main" class="product-list">
<h1>{% if category %}{{ category.name }}{% else %}Tovar{% endif %}</h1>
{% for product in products %}
<div class="item">
<a href="{{ product.get_absolute_url }}">
    <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}">
</a>
<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
<br>
${{ product.price }}
</div>
{% endfor %}
</div>
{% endblock %}

templates/shop/product/rate_product.html
{% extends 'base.html' %}

{% block content %}
  <h3>Оценить товар</h3>
  <form method="post" action="{% url 'rate_product' product.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Оценить</button>
  </form>
{% endblock %}